-- 004_words.sql
-- Create table for game words and seed initial values.

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  text text not null,                                  -- 단어 내용
  min_level int not null,                              -- 단어가 나타나는 최소 레벨
  max_level int not null                               -- 단어가 나타나는 최대 레벨
);

-- Seed initial sample values
-- Note: This is for initial setup. Add more words as needed.
insert into public.words(text, min_level, max_level) values
('하늘', 1, 3),
('바다', 1, 2),
('컴퓨터', 3, 6),
('무지개', 2, 4),
('인프라', 2, 3)
('인테리어', 3, 5),
('비행기', 2, 4),
('배', 1, 2),
('히틀러', 3, 4),
('구멍가게', 3, 5)
('놀면뭐하니', 4, 6),
('한국관광공사', 4, 7),
('놀이동산', 3, 6),
('멍청이', 2, 4),
('콩', 1, 2)
('윤도현', 2, 4),
('바다사자', 3, 5),
('오스트리아', 4, 7),
('대한민국', 3, 6),
('와장창', 2, 4)
on conflict (id) do nothing;

-- Enable RLS and allow anonymous read access
alter table public.words enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='words' and policyname='words_read'
  ) then
    create policy words_read on public.words
      for select to anon using (true);
  end if;
end $$;
