-- 1. 이전 마이그레이션에서 생성한 트리거와 함수를 먼저 삭제합니다.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- 2. 기존 players 테이블을 삭제합니다. (CASCADE를 사용하여 관련 객체 모두 삭제)
DROP TABLE IF EXISTS public.players CASCADE;

-- 3. 새로운 'players' 테이블 생성 (자체 인증용)
CREATE TABLE public.players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname text NOT NULL UNIQUE,
    hashed_password text NOT NULL,
    cumulative_points integer NOT NULL DEFAULT 0,
    level text NOT NULL DEFAULT 'Bronze Medal',
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. Comment 추가
COMMENT ON TABLE public.players IS '게임 사용자 정보, 자체 인증 및 누적 데이터를 저장합니다.';
COMMENT ON COLUMN public.players.nickname IS '사용자의 고유한 닉네임 (로그인 시 사용).';
COMMENT ON COLUMN public.players.hashed_password IS '안전하게 해시 처리된 사용자 비밀번호입니다.';
